CC ?= clang

CFLAGS += -std=gnu99 -Wall -DFAKE_STAT $(FAKETIME_COMPILE_CFLAGS)

SRC = timetest.c
OBJ = ${SRC:.c=.o}

all: timetest set_mtime time_ops_test test

.c.o:
	${CC} -c ${CFLAGS} $<

timetest: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS}

set_mtime: set_mtime.c
	${CC} -o $@ ${CFLAGS} $<

time_ops_test: time_ops_test.c ../src/time_ops.h
	${CC} -o $@ ${CFLAGS} $<

test: timetest time_ops_test set_mtime functest
	@echo
	@./time_ops_test
	@./test_OSX.sh

# run functional tests
functest:
	./testframe.sh functests

clean:
	@rm -f ${OBJ} timetest set_mtime time_ops_test

distclean: clean
	@echo

.PHONY: all test clean distclean
